SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, 
COUNT(DISTINCT(O.USER_ID)) AS PURCHASED_USERS,
ROUND (COUNT(DISTINCT O.USER_ID) / 
       (SELECT COUNT(U.USER_ID) FROM USER_INFO U WHERE YEAR(U.JOINED) = 2021)
       ,1) AS PURCHASED_RATIO
FROM USER_INFO U RIGHT JOIN ONLINE_SALE O 
ON U.USER_ID = O.USER_ID
WHERE YEAR(U.JOINED) =2021
GROUP BY MONTH
ORDER BY YEAR, MONTH