SELECT I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES
FROM REST_INFO I
INNER JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
            FROM REST_INFO
            GROUP BY FOOD_TYPE) I2
        ON I.FOOD_TYPE = I2.FOOD_TYPE AND I.FAVORITES = I2.FAVORITES
ORDER BY FOOD_TYPE DESC